# Generated by Django 4.2.2 on 2023-06-29 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoProducto',
            fields=[
                ('idTipoProducto', models.AutoField(db_column='idTipop', primary_key=True, serialize=False, verbose_name='ID_tipo_Producto')),
                ('tipoProducto', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipoProducto', models.ForeignKey(db_column='idTipop', on_delete=django.db.models.deletion.CASCADE, to='alumnos.tipoproducto')),
            ],
        ),
    ]
